import random
from typing import Sequence

# 50+ DnD-style but people-friendly answers
_ANSWERS_RU: Sequence[str] = [
    "Определённо да.",
    "Судьба благоволит.",
    "Знаки указывают на ‘да’.",
    "Да, если приложишь усилия.",
    "Да, но не сразу.",
    "Да, хотя цена будет высокой.",
    "Скорее да, чем нет.",
    "Ответ туманен — попробуй позже.",
    "Сначала задай правильный вопрос.",
    "Сконцентрируйся, и ответ проявится.",
    "Время пока не пришло.",
    "Подожди удачного момента.",
    "Слишком рискованно.",
    "Шанс невелик.",
    "Нет — по крайней мере сейчас.",
    "Скорее нет.",
    "Нет, это отвлечёт от главного.",
    "Нет — ты уже знаешь почему.",
    "Не сейчас. Пересмотри план.",
    "Нужно больше информации.",
    "Выбери проще путь.",
    "Спроси совет у наставника.",
    "Проверь допущения и вернись.",
    "Твой внутренний голос говорит ‘да’.",
    "Твоя интуиция говорит ‘нет’.",
    "Монета упала на ребро — решай сам.",
    "Сделай маленький шаг вперёд.",
    "Отпусти — и ответ проявится.",
    "Дорога открыта.",
    "Дверь закрыта. Ищи ключ.",
    "Шансы 50/50.",
    "Да, если действуешь сегодня.",
    "Да, но не в одиночку.",
    "Да — при поддержке друзей.",
    "Следуй плану — получится.",
    "Смени подход — и ответ станет ‘да’.",
    "Удача на твоей стороне.",
    "Случай благоприятствует смелым.",
    "Тени сомнений густеют — нет.",
    "Слишком много неизвестных.",
    "Спроси себя: зачем это тебе?",
    "Разве это действительно важно?",
    "Посмотри под другим углом.",
    "Собери факты — тогда решай.",
    "Выспись — ответ придёт утром.",
    "Да, если поставишь чёткую цель.",
    "Нет, пока не укрепишь основы.",
    "Да — путь открыт и ясен.",
    "Нет — вернись к истокам.",
    "Ответ скрыт в простоте.",
    "Доверяй процессу.",
]

_ANSWERS_EN: Sequence[str] = [
    "Definitely yes.",
    "Fate favors you.",
    "All signs point to yes.",
    "Yes, if you put in the effort.",
    "Yes, but not right away.",
    "Yes, though the price is high.",
    "More yes than no.",
    "Answer is hazy — ask later.",
    "First, ask the right question.",
    "Focus and the answer will appear.",
    "The time hasn’t come yet.",
    "Wait for a better moment.",
    "Too risky.",
    "Odds are slim.",
    "No — at least for now.",
    "Leaning no.",
    "No, it distracts from what matters.",
    "No — you already know why.",
    "Not now. Rework the plan.",
    "You need more information.",
    "Choose the simpler path.",
    "Seek counsel from a mentor.",
    "Check your assumptions and return.",
    "Your inner voice says yes.",
    "Your gut says no.",
    "Coin stands on its edge — your call.",
    "Take one small step forward.",
    "Let go — the answer will surface.",
    "The road is open.",
    "The door is closed. Find the key.",
    "It’s 50/50.",
    "Yes, if you act today.",
    "Yes, but not alone.",
    "Yes — with help from friends.",
    "Stick to the plan — it’ll work.",
    "Change approach — answer turns yes.",
    "Luck is on your side.",
    "Fortune favors the bold.",
    "Shadows grow thicker — no.",
    "Too many unknowns.",
    "Ask yourself: why do you want this?",
    "Is this truly important?",
    "View it from another angle.",
    "Gather facts — then decide.",
    "Sleep on it — answer by morning.",
    "Yes, if you set a clear goal.",
    "No, not until you build the basics.",
    "Yes — the path is open and clear.",
    "No — return to fundamentals.",
    "The answer hides in simplicity.",
    "Trust the process.",
]


def pick_answer(lang: str) -> str:
    items = _ANSWERS_RU if lang == "ru" else _ANSWERS_EN
    return random.choice(items)
