from __future__ import annotations

import random
from typing import Sequence


# 100+ цитат: микс мудрых, мотивирующих и немного ироничных
_QUOTES_RU: list[str] = [
    "Не обязательно делать много. Главное — делать регулярно.",
    "Идеального момента не будет. Есть только сейчас.",
    "Самый сложный шаг — первый. Остальные идут по инерции.",
    "Дисциплина сильнее мотивации.",
    "Если хочешь иметь то, чего никогда не имел, делай то, чего никогда не делал.",
    "Ошибки — это плата за опыт.",
    "Вчера уже не изменить, но сегодня ещё можно настроить.",
    "Кто ищет идеальные условия, тот редко начинает.",
    "Не сравнивай свой старт с чужой серединой.",
    "Лучший день, чтобы начать, был вчера. Второй лучший — сегодня.",
    "Тебе не нужно быть лучшим — достаточно быть лучше, чем вчера.",
    "Тишина тоже ответ, просто не всегда приятный.",
    "Иногда самое продуктивное, что можно сделать, — выдохнуть.",
    "Если долго смотреть на проблему, она начнёт смотреть на тебя.",
    "Не откладывай на понедельник то, что спокойно можно не сделать никогда.",
    "Никто не знает, что делает. Просто кто-то делает вид уверенно.",
    "Сначала ты работаешь на репутацию, потом репутация работает на тебя.",
    "Устал — отдохни, а не сдайся.",
    "Ничего не делать тоже трудно — совесть мешает.",
    "Планы не работают. Работают люди, у которых есть планы.",
    "Хочешь быстрый результат — посади редис. Хочешь серьёзный — сажай привычку.",
    "Иногда правильный путь — самый тихий.",
    "Задача не в том, чтобы успеть всё, а в том, чтобы успеть важное.",
    "У чудес странный график — они приходят к тем, кто не сдался.",
    "Если что-то можно объяснить ленью, не ищи глубинных причин.",
    "Сегодняшний дискомфорт — завтрашняя свобода.",
    "Нет настроения? Делай по инструкции, настроение подтянется.",
    "Сомнения съедают больше энергии, чем работа.",
    "Мечты бесплатны, но реализация по подписке — ежедневной.",
    "Когда не знаешь, с чего начать — начни с малого.",
    "Большие изменения начинаются с маленького, но регулярного действия.",
    "Если путь кажется лёгким, проверь, туда ли ты идёшь.",
    "Не жалуйся на результат работы, которую ты не сделал.",
    "Лень — это сигнал, что у задачи нет смысла. Или у тебя нет сна.",
    "Хаос вокруг часто начинается с хаоса внутри.",
    "Стабильность — это не отсутствие изменений, а умение ими управлять.",
    "Лучше маленький шаг каждый день, чем рывок раз в полгода.",
    "Когда кажется, что прогресса нет, посмотри назад, а не по сторонам.",
    "Никто не придёт и не сделает за тебя твой отжимание.",
    "Иногда главное достижение дня — не удалить всё к чёрту.",
    "Самое сложное — не начать, а продолжать, когда новизна прошла.",
    "Ты не обязан быть продуктивным всегда. Но ты можешь быть честным с собой.",
    "Чем дольше откладываешь простой шаг, тем страшнее он кажется.",
    "Если нет плана на день, день пройдёт по чужому плану.",
    "Сделанное несовершенно лучше, чем идеальное, но несделанное.",
    "Не ищи мотивацию — убери лишние препятствия.",
    "Выбор «полчаса телефона» или «полчаса дела» повторяется каждый день.",
    "Ты можешь не верить в себя. Просто сделай вид, что веришь — и действуй.",
    "Иногда прогресс — это не вперёд, а вовремя остановиться.",
    "Когда голова полна мыслей, список задач — лучший психотерапевт.",
    "Сознательная пауза — тоже действие.",
    "Не усложняй. Один шаг. Один фокус. Один день.",
    "Лучше быть стабильным середняком, чем гением, который так и не начал.",
    "Если не знаешь, с чего начать — начни с воды и зарядки.",
    "Люди переоценивают день и недооценивают год.",
    "Вдохновение приходит во время работы, а не перед ней.",
    "Шанс — это дверь. Но ручка всегда с твоей стороны.",
    "Когда нет сил, делай минимум. Минимум — это не ноль.",
    "Каждое «не сегодня» потихоньку превращается в «никогда».",
    "Состояние «я ничего не успеваю» лечится словом «приоритеты».",
    "Не все шумные дела важны, и не все важные дела шумят.",
    "Ты не обязан быть лучше всех. Но ты можешь быть надёжным для себя.",
    "Никто не видит 90% работы, но все видят результат. И это нормально.",
    "Когда хочется всё бросить, брось ожидания, а не путь.",
    "Смена окружения — это тоже инструмент, а не каприз.",
    "Иногда «ещё один шанс» нужно дать не делу, а себе.",
    "Ты можешь двигаться медленно. Главное — не в обратную сторону.",
    "Если план слишком красивый — проверь, реален ли он.",
    "Делегировать можно всё, кроме ответственности за свою жизнь.",
    "Твой опыт — это твой внутренний капитал. Береги и приумножай.",
    "Результат не обязан быть быстрым, но он обязан быть честным.",
    "Один честно сделанный день стоит недели самообмана.",
    "Иногда лучший лайфхак — лечь спать вовремя.",
    "Прогресс — это когда вчерашние сложности стали сегодняшней рутиной.",
    "Каждый раз, когда ты говоришь «потом», подумай, кто за это заплатит — ты же.",
    "Не все победы выглядят громко. Иногда это просто «я всё-таки сделал».",
    "Жизнь — это не спринт и не марафон, это длинная прогулка с остановками.",
    "Если хочешь изменений — добавь их в календарь, а не в желания.",
    "Хочешь, как в кино? Там тоже всегда есть монтаж труда, просто его проматывают.",
    "Иногда правильный шаг — сказать «нет» даже себе.",
    "Твой завтрашний комфорт зависит от сегодняшней дисциплины.",
    "Когда всё лень — начни с трёх минут. Три минуты выдержит любой.",
    "Большинство вопросов решается не перепиской, а действием.",
    "Если ты не управляешь вниманием, кто-то управляет им за тебя.",
    "Небольшой прогресс каждый день — это не скучно, это магия сложных процентов.",
    "Внутренний критик редко бывает продуктивным консультантом.",
    "Иногда лучший план — сделать один маленький шаг и посмотреть, что изменится.",
    "Если хочешь стабильности — сделай стабильным своё поведение, а не обстоятельства.",
    "Ты не обязан делать всё идеально. Ты обязан быть честным с собой.",
    "Успех — это множество тихих «сделал», а не одно громкое «получилось».",
]

_QUOTES_EN: list[str] = [
    "You don't need more time, you need more focus.",
    "There is no perfect moment. There is only now.",
    "The hardest step is the first one. The rest follow by inertia.",
    "Discipline beats motivation.",
    "If you want something you've never had, do something you've never done.",
    "Mistakes are tuition for experience.",
    "You can't change yesterday, but you can tune today.",
    "Those who wait for perfect conditions rarely start.",
    "Don't compare your start to someone else's middle.",
    "The best day to start was yesterday. The second best is today.",
    "You don't need to be the best — just better than yesterday.",
    "Silence is also an answer, just not always a pleasant one.",
    "Sometimes the most productive thing you can do is exhale.",
    "If you stare at a problem long enough, it starts staring back.",
    "Don't postpone to Monday what you can happily never do.",
    "Nobody really knows what they're doing. Some are just better at acting confident.",
    "First you work for your reputation, then your reputation works for you.",
    "Tired? Rest, don't quit.",
    "Doing nothing is hard too — conscience gets in the way.",
    "Plans don't work. People with plans do.",
    "If you want fast results, plant radishes. If you want serious ones, plant habits.",
    "Sometimes the right path is the quietest one.",
    "The goal is not to do everything, but to do what matters.",
    "Miracles have a strange schedule — they visit those who didn't give up.",
    "If laziness explains it, don't look for deeper reasons.",
    "Today's discomfort is tomorrow's freedom.",
    "No mood? Follow the instructions, the mood will follow.",
    "Doubts drain more energy than work.",
    "Dreams are free, execution is a daily subscription.",
    "When you don't know where to start, start small.",
    "Big changes are built from small, consistent actions.",
    "If the road feels too easy, check the destination.",
    "Don't complain about results of work you never did.",
    "Laziness is often a signal that the task has no meaning — or that you need sleep.",
    "Chaos outside often begins with chaos inside.",
    "Stability isn't absence of change, it's ability to navigate it.",
    "Better a tiny step every day than a huge leap once in a while.",
    "When it feels like there's no progress, look back, not sideways.",
    "No one will do your push-ups for you.",
    "Sometimes the biggest win of the day is not rage‑quitting.",
    "The hardest part isn't starting, it's continuing after the novelty is gone.",
    "You don't have to be productive all the time. Just honest with yourself.",
    "The longer you delay a simple step, the scarier it becomes.",
    "If you don't have a plan for the day, the day will follow someone else's.",
    "Done imperfect beats perfect undone.",
    "Don't hunt for motivation — remove friction instead.",
    "Every day you choose between half an hour of your phone and half an hour of your life.",
    "You may not believe in yourself. Pretend you do — and act.",
    "Sometimes progress is not forward but stopping in time.",
    "When your mind is noisy, a todo list is free therapy.",
    "A conscious pause is also an action.",
    "Don't overcomplicate. One step. One focus. One day.",
    "Better a consistent average than a genius who never starts.",
    "If you don't know where to start — start with water and a walk.",
    "People overestimate a day and underestimate a year.",
    "Inspiration shows up during work, not before it.",
    "Opportunity is a door. The handle is always on your side.",
    "When you have no energy, do the minimum. Minimum is not zero.",
    "Every \"later\" quietly turns into \"never\".",
    "The phrase \"I'm so busy\" is often a synonym for \"I have no priorities\".",
    "Not all noisy tasks are important, and not all important tasks make noise.",
    "You don't have to be better than everyone. Just be reliable for yourself.",
    "Most of the work is invisible. The result is not — and that's fine.",
    "When you want to quit, quit the expectations, not the path.",
    "Changing your environment is a tool, not a whim.",
    "Sometimes the second chance should be given not to the task, but to yourself.",
    "You can move slowly. Just don't walk backwards.",
    "If the plan looks too pretty, check if it's realistic.",
    "You can delegate almost everything except responsibility for your life.",
    "Your experience is your inner capital. Protect and grow it.",
    "Results don't have to be fast, but they must be honest.",
    "One honest day of work beats a week of self‑deception.",
    "Sometimes the best lifehack is going to bed on time.",
    "Progress is when yesterday's difficulties become today's routine.",
    "Every time you say \"not today\", ask who will pay for it — future you.",
    "Not every victory is loud. Sometimes it's just \"I still showed up\".",
    "Life is neither a sprint nor a marathon — it's a long walk with stops.",
    "If you want change, put it in your calendar, not in your wishes.",
    "Want it like in the movies? There is always a montage of work, they just skip it.",
    "Sometimes the right move is to say no — even to yourself.",
    "Your future comfort is funded by today's discipline.",
    "When everything feels like too much, start with three minutes. Anyone can survive three minutes.",
    "Most problems are solved not by chatting but by doing.",
    "If you don't control your attention, someone else gladly will.",
    "Small daily progress isn't boring — it's compound interest.",
    "Your inner critic is rarely a good coach.",
    "Sometimes the best plan is one small step and see what changes.",
    "If you want stability, stabilize your behavior, not the world.",
    "You don't have to do everything perfectly. You do have to be honest with yourself.",
    "Success is many quiet \"done\"s, not one loud \"wow\".",
]


def get_all(lang: str) -> Sequence[str]:
    return _QUOTES_RU if lang == "ru" else _QUOTES_EN


def get_total() -> int:
    return len(_QUOTES_RU)


def get_by_id(qid: int, lang: str) -> str:
    items = get_all(lang)
    if qid < 1 or qid > len(items):
        raise IndexError("quote id out of range")
    return items[qid - 1]
